clusterroles = ['admin', 'cluster-admin', 'edit', 'kubeadm:get-nodes', 'system:aggregate-to-admin',
                'system:aggregate-to-edit', 'system:aggregate-to-view', 'system:auth-delegator',
                'system:basic-user', 'system:certificates.k8s.io:certificatesigningrequests:nodeclient',
                'system:certificates.k8s.io:certificatesigningrequests:selfnodeclient',
                'system:certificates.k8s.io:kube-apiserver-client-approver',
                'system:certificates.k8s.io:kube-apiserver-client-kubelet-approver',
                'system:certificates.k8s.io:kubelet-serving-approver',
                'system:certificates.k8s.io:legacy-unknown-approver',
                'system:controller:attachdetach-controller', 'system:controller:certificate-controller',
                'system:controller:clusterrole-aggregation-controller', 'system:controller:cronjob-controller',
                'system:controller:daemon-set-controller', 'system:controller:deployment-controller',
                'system:controller:disruption-controller', 'system:controller:endpoint-controller',
                'system:controller:endpointslice-controller',
                'system:controller:endpointslicemirroring-controller',
                'system:controller:ephemeral-volume-controller', 'system:controller:expand-controller',
                'system:controller:generic-garbage-collector', 'system:controller:horizontal-pod-autoscaler',
                'system:controller:job-controller', 'system:controller:namespace-controller',
                'system:controller:node-controller', 'system:controller:persistent-volume-binder',
                'system: controller:pod-garbage-collector', 'system:controller:pv-protection-controller',
                'system:controller:pvc-protection-controller', 'system:controller:replicaset-controller',
                'system:controller:replication-controller', 'system:controller:resourcequota-controller',
                'system:controller:root-ca-cert-publisher', 'system:controller:route-controller',
                'system:controller:service-account-controller', 'system:controller:service-controller',
                'system:controller:statefulset-controller', 'system:controller:ttl-after-finished-controller',
                'system:controller:ttl-controller', 'system:coredns', 'system:discovery', 'system:heapster',
                'system:kube-aggregator', 'system:kube-controller-manager', 'system:kube-dns',
                'system:kube-scheduler', 'system:kubelet-api-admin', 'system:monitoring', 'system:node',
                'system:node-bootstrapper', 'system:node-problem-detector', 'system:node-proxier',
                'system:persistent-volume-provisioner', 'system:public-info-viewer',
                'system:service-account-issuer-discovery', 'system:volume-scheduler', 'view',
                'system:cloud-controller-manager', 'cert-manager-csf-cert-manager-controller-challenges',
                'cert-manager-csf-cert-manager-controller-clusterissuers', 'cert-manager-csf-cert-manager-cainjector',
                'cert-manager-csf-cert-manager-controller-certificates',
                'cert-manager-csf-cert-manager-controller-issuers', 'csi-snapshotter-role',
                'nfs-external-provisioner-role', 'cert-manager-csf-cert-manager-controller-orders',
                'csi-cephrbd-provisioner', 'csi-cephfs-provisioner']

roles = ['kubeadm:bootstrap-signer-clusterinfo', 'system:controller:bootstrap-signer',
         'extension-apiserver-authentication-reader', 'kube-proxy', 'kubeadm:kubelet-config',
         'kubeadm:nodes-kubeadm-config', 'system:leader-locking-kube-controller-manager',
         'system:leader-locking-kube-scheduler', 'system:controller:bootstrap-signer',
         'system:controller:cloud-provider', 'system:controller:token-cleaner',
         'system:persistent-volume-provisioner']
